services:
  - type: web
    name: contentflow-waitlist
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: contentflow-db
          property: connectionString
    buildFilter:
      paths:
      - package.json
      - package-lock.json
      - client/**
      - server/**
      - shared/**
      - vite.config.ts
      - tailwind.config.ts
      - tsconfig.json

databases:
  - name: contentflow-db
    databaseName: contentflow